---
repos:
  - repo: https://github.com/codespell-project/codespell
    rev: 63c8f8312b7559622c0d82815639671ae42132ac  # frozen: v2.4.1
    hooks:
      - id: codespell
        args: ["--ignore-words-list", "edn", "--ignore-regex=.*codespell-ignore$", "--skip", "*.json"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: >-
          (?x)^(
          .*\.(log|svg)
          )$
      - id: check-yaml
      - id: end-of-file-fixer
      - id: debug-statements
      - id: name-tests-test
      - id: requirements-txt-fixer
      - id: detect-private-key
      - id: destroyed-symlinks
      - id: check-shebang-scripts-are-executable
      - id: check-case-conflict
      - id: check-ast
      - id: check-builtin-literals
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: mixed-line-ending

  - repo: https://github.com/codespell-project/codespell
    rev: 63c8f8312b7559622c0d82815639671ae42132ac  # frozen: v2.4.1
    hooks:
      - id: codespell
        exclude: >-
          (?x)^(
          .*\.(log|svg)
          )$
